### ISSUE TITLE
Crash on load with .dat files

### ISSUE THREAD

**Issue by KrisKingo** [nikez/gtav_audio_occlusion_documentation#3]
My game crash when i load .dat15 and .dat151 files.
I tried all day yesterday to find out why it does that, but no hope..
It could be greate if anyone wanna explain why it does that, because i have now spent many hours and no luck..

**Map download**
https://forum.cfx.re/t/mlo-secret-weapons-room/1877982

**Files (github only allowes .txt)**
[fxmanifest.lua.txt](https://github.com/nikez/gtav_audio_occlusion_documentation/files/6343568/fxmanifest.lua.txt)
[gigz_shell_weapon_room_col_game.dat151.rel.txt](https://github.com/nikez/gtav_audio_occlusion_documentation/files/6343569/gigz_shell_weapon_room_col_game.dat151.rel.txt)
[gigz_shell_weapon_room_col_mix.dat15.rel.txt](https://github.com/nikez/gtav_audio_occlusion_documentation/files/6343570/gigz_shell_weapon_room_col_mix.dat15.rel.txt)
[gigz_int_weapon_room_milo_.ymap.txt](https://github.com/nikez/gtav_audio_occlusion_documentation/files/6343575/gigz_int_weapon_room_milo_.ymap.txt)

**Comment by KrisKingo** [comment]
Tried every thing.
Crash report when i try loading my .ymt
[CfxCrashDump_2021_04_20_17_23_08.zip](https://github.com/nikez/gtav_audio_occlusion_documentation/files/6346273/CfxCrashDump_2021_04_20_17_23_08.zip)

**Comment by nikez** [comment]
Using stolen assets - deserves no help. Filthy.

**Comment by KrisKingo** [comment]
How is it stolen?
Its on the forums?

**Comment by KrisKingo** [comment]
Nikez, i haven't sat three days straight to learn and help the community for nothing.
I'm not using leaked assets to ruin the community or gain anything, i'm hear to learn something new, and help the community..
Please, i hope you understand, that i'm not trying to run a server, or trying to gain any money from this, im just hear for learning something and helping out. I've been talking to other people that have been in my position and we are still here.
There soo much potential in Audio Occlusion and i think we can help eachother 😄 
It's not because im a guy using leaks.. I've bougt many things from Gabz, and even Hayes Auto to try and fix my problems with Audio Occlusion, because i saw you one day stream you making Audio Occlusion in Hayes Auto.
I hope you don't see me as a bad guy, but a guy trying to learn something new and helping out the community!
Im really sorry..
Kind regards, Kris.

**Comment by nikez** [comment]
> How is it stolen?
> Its on the forums?

One of the file you uploaded to cfx.re forums was "denis3d_impound_office_milo_.ymap", correct? The same post that not longer exists because it was removed by moderators as it was a stolen asset?

I do not give a fuck if you have a server or not, using stolen assets is scummy and you do not deserve any help. This documentation was enough for me to generate occlusion files, it's on you.

**Comment by nikez** [comment]
And this is the post that is now removed, if anyone is curious. I don't really get how you thought approaching me about help with stolen assets from the server I work on would ever be a good idea. **Shame on you.**

![image](https://user-images.githubusercontent.com/1504588/115551396-47a47680-a2ab-11eb-9e7e-6d2ead6596f2.png)

**Comment by KrisKingo** [comment]
Yeah, and it is scummy, not doubt.
And theres nothing more i can say, and it is/was scummy, but atleast i hope you know, that i was not using it, more testing it with Audio Occlusion. I'm sorry, theres nothing i can say more. It's more that just what you think.. 
One of the reason i even thought of using a leaked asset from NoPixel was to see if it would still crash, i didn't know if it could have something to do with how the MLO is build.

**Comment by KrisKingo** [comment]
I'm not trying to hide the fact that i was using a leaked assets, because i was.
I was just so frustrated over it not working after +36 hours of trying to fix it, then i thought of the idea that i could have something with the MLO. At first i litterally bought gabz hayes auto to see if it will worked, but sadly no. So if it worked on your server, i could try one of your MLO's, but that was a great idea, wasn't it..?

**Comment by nikez** [comment]
Does the documentation reference anything about altering MLO's? No? Why do you think I'd omit important information in a post explaining in _detail_ on how to generate such files? You may have spent 3 days on trying to figure out something that is already figured out and **documented**, it still does not excuse your shitty behavior in any way.

Why would you not check the **ROCKSTAR BUILDINGS** WHERE IT ALREADY WORKS?!?!?!??!?!?!?!?!

**Comment by KrisKingo** [comment]
I does work with Rockstar buildings, its not that im saying?
I wrote earlier that my .ymt is crashing, that is the problem. That is the problem i still have, and can't figure out why.
So i thougt it had something to do with how the MLO is build, and it could maybe not handle Audio Occlusion. Just because im not a experienced developer, i don't have to know everything? And something thats not documented is trouble shooting...
So how would i ever know why my .ymt is crashing my game..?

**Comment by nikez** [comment]
You're still trying to justify your behavior, get out of here. I literally just told you; THERE IS NOTHING REQUIRED FROM THE MLO's OR IT'D SAY SO IN THE DOCUMENTATION.

Now stop writing, filth.

**Comment by KrisKingo** [comment]
Bro, you still don't explain why its crashing then..
How would i ever know why its crashing.. So i must think of something myself, because its not documentated...
Im not using leaked assets on the daily, its soooo scummy and thats why im buy it. https://cdn.discordapp.com/attachments/725090406907248781/834404918860447754/image0.png

**Comment by nikez** [comment]
Yet you asked for my help with a leaked asset. Great character.

Do it properly and it wont crash :) I have no obligation to fix your shit, this documentation is my contribution and if I made it work on 200+ interiors, I don't see why anyone else wouldn't be able to. Now get out.

**Comment by KrisKingo** [comment]
The difference is that you also use a Audio Occlusion program..
Theres something that must be missing, becuase i did EVERYTHING and its still crashing EVEN IN GABZ hayes auto..
I'm not asking you to "fix" my shit, just the help out how i can fix the crashes, that would maybe also help other that have problems crashing. Bro i hope you will understand.. I'm not here for doing scummy things, i'm just trying to improve the documentation if i run into anything.. And clearly i am. If people as me getting problems, it can be included in the documentation and help further problems..

**Comment by nikez** [comment]
A program.... made purely out of this research and documentation :) Others have succeeded with this documentation, so I don't see the documentation as an issue, just the reader.

**Comment by KrisKingo** [comment]
Yeah haha well it is the reader 
But it could just be great to see some sort of trouble shoot documentation.

**Comment by KrisKingo** [comment]
I think you should take this issues as a help to improve the documentation.
I think you shouldn't react like im selling a stupid MLO or trying to ruin everything for you.
Its a stupid crash that have made this big discussion and its really stupid and dumb.
So Nikez, will you please forget this, and not take this as a criticism, hate or anything bad, but attempt to make Audio Occlusion more, lets call it "newb" friendly, so that everyone can follow through it?
I will still try to fix this issues, and i would probally take me many hours, but at the end of the day, i didn't make any money of this, and i didn't do any bad things for you.
Have a good day Nikez
