### ISSUE TITLE
FiveM Crash when streaming dat151

### ISSUE THREAD

**Issue by zoovdev** [nikez/gtav_audio_occlusion_documentation#5]
I've followed this guide and i keep checking and comparing it with all the documentation and everything seems like it should work. However when i attempt to stream the file, using the correct fxmanifest (as given in the documentation) the game crashes as it loads giving an error message stating : 

"class audMetadataDataFileMounter." linking to the dat151 file.

**Comment by Smokiiee** [comment]
![image](https://user-images.githubusercontent.com/70150561/144456926-fc4e0930-0901-4aea-8ced-f26aae1ae9bb.png)
 even have error on driving_school.dat

**Comment by Smokiiee** [comment]
I fixt it @zoovenem :)

**Comment by NickMrFree** [comment]
> I fixt it @zoovenem :)

how do you fixed it? i need help :)

**Comment by Smokiiee** [comment]
> > I fixt it @zoovenem :)
> 
> how do you fixed it? i need help :)

after you received the dat files. convert it back in to codewalker then export them

**Comment by ExpertOp** [comment]
> how can i convert it in to codewalker : <

**Comment by Smokiiee** [comment]
> 

codewalker rpf
@ExpertOp
