### ISSUE TITLE
FiveM can only run occlusions for a single map

### ISSUE THREAD

**Issue by junior99au** [nikez/gtav_audio_occlusion_documentation#6]
So when you use this method to make another set of audio occlusions for another map so for example I have:
MLO - Warehouse
MLO - Mafia

And we make occlusions for Warehouse and run it they work, then we make it for Mafia and start that resource 2nd in the config, Occlusions will work for Warehouse but not mafia, if we disable warehouse and its occlusions then occlusions will work for Mafia. Is there a way to run both sets of audio occlusions?

**Comment by st860923** [comment]
FiveM seems only support one occlusion files.
so you need to merge it to single file. and stream onec.

**Comment by Kaparrs** [comment]
I haven't had any problems running more than one resource with occlusion files inside of it

**Comment by Kaparrs** [comment]
One way how to counter your issue is combining both occlusion data files together what Nikez does, but I think he has made custom tools to do it for him
